/* AUTO-GENERATED FILE.  DO NOT MODIFY.
 *
 * This class was automatically generated by the
 * aapt tool from the resource data it found.  It
 * should not be modified by hand.
 */

package org.me.radio105alarm;

public final class R {
    public static final class array {
        public static final int week_days_array=0x7f050000;
    }
    public static final class attr {
    }
    public static final class drawable {
        public static final int button_pause=0x7f020000;
        public static final int button_play=0x7f020001;
        public static final int calculator=0x7f020002;
        public static final int calendar=0x7f020003;
        public static final int camera=0x7f020004;
        public static final int picture_frame=0x7f020005;
    }
    public static final class id {
        public static final int Logo=0x7f070001;
        public static final int MainFlipper=0x7f070006;
        public static final int MediaPlayer=0x7f070007;
        public static final int WeekDays=0x7f070000;
        public static final int button_play=0x7f070002;
        public static final int button_stream=0x7f070004;
        public static final int edit_alarm=0x7f070008;
        public static final int progress_bar=0x7f070005;
        public static final int text_kb_streamed=0x7f070003;
    }
    public static final class layout {
        public static final int edit_alarm=0x7f030000;
        public static final int main=0x7f030001;
    }
    public static final class menu {
        public static final int radio_menu=0x7f060000;
    }
    public static final class string {
        public static final int app_name=0x7f040000;
        public static final int edit_alarm=0x7f040001;
    }
}
